export interface Todo {
  id: string;
  title: string;
  description?: string;
  status: string;
  priority: string;
  source: string;
  execution_mode: string;
  source_ref?: string;
  owner_id?: string;
  original_owner_id?: string;
  target_user_id?: string;
  task_flow_type?: string;
  last_flow_state?: string | null;
  last_flow_type?: string | null;
  due_date?: string;
  completed_at?: string;
  tags: string[];
  responsibility_ids: string[];
  responsibility_titles: string[];
  project?: string;
  review_status?: string;
  review_reason?: string;
  orchestration_id?: string;
  is_recurring: boolean;
  recurrence_cron?: string;
  recurrence_count: number;
  created_at: string;
  updated_at: string;
}
